version: '3.8'

services:
  checkit-app:
    container_name: checkit-app
    image: 192.168.1.222:5555/wesp/checkit-app
    restart: unless-stopped
    command: yarn workspace @wesp-up/checkit-app start
    ports:
      - 2016:3000
    env_file:
      - .env
    environment:
      - SITE_PROTOCOL=https
      - SITE_HOST=checkit.sunbeam1.page
      - SITE_PORT=
      - DATABASE_HOST=checkit-mongo
      - LOG_PATH=/logs
  checkit-mongo:
    container_name: checkit-mongo
    image: mongo
    restart: unless-stopped
    volumes:
      - ./mongo:/data/db
